version: '3'
services:
  nginx:
    image: quay.io/akiray03/nginx-fastcertificate
    # build: ./build
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs:/usr/local/nginx/logs
    links:
      - redis:redis
    environment:
      NGINX_WORKER_PROCESSES: 2
      REDIS_HOST: "redis"
      SSL_DOMAINS: "test.ssltest.yumiyama.com test2.ssltest.yumiyama.com test3.ssltest.yumiyama.com"
      test_ssltest_yumiyama_com_PROXY_TO_HOST: INTERNAL_IP
      test_ssltest_yumiyama_com_PROXY_TO_PORT: '3000'
    depends_on:
      - redis

  redis:
    image: redis:3.2-alpine
    expose:
      - '6379'
