version: '3'
services:
  nginx:
    image: quay.io/akiray03/nginx-fastcertificate
    # build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs:/usr/local/nginx/logs
    links:
      - redis:redis
    environment:
      REDIS_HOST: "redis"
      SSL_DOMAINS: "test.ssltest.yumiyama.com test2.ssltest.yumiyama.com test3.ssltest.yumiyama.com"
      test.ssltest.yumiyama.com_PROXY_TO_HOST: 127.0.0.1
      test.ssltest.yumiyama.com_PROXY_TO_PORT: '3000'
    depends_on:
      - redis

  redis:
    image: redis:3.2-alpine
    expose:
      - '6379'
